spring:
  application:
    name: websocket
  mongodb:
    uri: ***REMOVED***
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

server:
  port: 8088

app:
  auth:
    cookie-secure: false
  upload:
    dir: uploads
