export const EMOJIS: Array<{ label: string; emoji: string }> = [
  { label: 'grinning', emoji: '😀' },
  { label: 'smile', emoji: '😄' },
  { label: 'joy', emoji: '😂' },
  { label: 'rofl', emoji: '🤣' },
  { label: 'wink', emoji: '😉' },
  { label: 'blush', emoji: '😊' },
  { label: 'heart eyes', emoji: '😍' },
  { label: 'thinking', emoji: '🤔' },
  { label: 'cool', emoji: '😎' },
  { label: 'star struck', emoji: '🤩' },
  { label: 'sleepy', emoji: '😴' },
  { label: 'surprised', emoji: '😮' },
  { label: 'confused', emoji: '😕' },
  { label: 'sad', emoji: '😢' },
  { label: 'crying', emoji: '😭' },
  { label: 'angry', emoji: '😠' },
  { label: 'rage', emoji: '😡' },
  { label: 'shush', emoji: '🤫' },
  { label: 'hushed', emoji: '😯' },
  { label: 'zipper mouth', emoji: '🤐' },
  { label: 'wave', emoji: '👋' },
  { label: 'thumbs up', emoji: '👍' },
  { label: 'clap', emoji: '👏' },
  { label: 'raised hands', emoji: '🙌' },
  { label: 'folded hands', emoji: '🙏' },
  { label: 'victory', emoji: '✌️' },
  { label: 'rock on', emoji: '🤘' },
  { label: 'fire', emoji: '🔥' },
  { label: '100', emoji: '💯' },
  { label: 'party', emoji: '🎉' },
  { label: 'tada', emoji: '🎊' },
  { label: 'heart', emoji: '❤️' },
  { label: 'red heart', emoji: '♥️' },
  { label: 'broken heart', emoji: '💔' },
  { label: 'heart sparkles', emoji: '💖' },
  { label: 'revolving hearts', emoji: '💞' },
  { label: 'star', emoji: '⭐' },
  { label: 'sparkles', emoji: '✨' },
  { label: 'clinking glasses', emoji: '🥂' },
  { label: 'coffee', emoji: '☕' },
  { label: 'beer', emoji: '🍺' },
  { label: 'pizza', emoji: '🍕' },
  { label: 'hamburger', emoji: '🍔' },
  { label: 'cake', emoji: '🎂' },
  { label: 'ice cream', emoji: '🍦' },
  { label: 'taco', emoji: '🌮' },
  { label: 'sushi', emoji: '🍣' },
  { label: 'rocket', emoji: '🚀' },
  { label: 'airplane', emoji: '✈️' },
  { label: 'sun', emoji: '☀️' },
  { label: 'moon', emoji: '🌙' },
  { label: 'rainbow', emoji: '🌈' },
  { label: 'snowman', emoji: '⛄' },
  { label: 'dog', emoji: '🐶' },
  { label: 'cat', emoji: '🐱' },
  { label: 'fox', emoji: '🦊' },
  { label: 'panda', emoji: '🐼' },
  { label: 'turtle', emoji: '🐢' },
  { label: 'unicorn', emoji: '🦄' },
  { label: 'cactus', emoji: '🌵' },
  { label: 'cherry blossom', emoji: '🌸' },
  { label: 'light bulb', emoji: '💡' },
  { label: 'gift', emoji: '🎁' },
  { label: 'trophy', emoji: '🏆' },
  { label: 'medal', emoji: '🥇' },
  { label: 'check mark', emoji: '✅' },
  { label: 'cross mark', emoji: '❌' },
  { label: 'warning', emoji: '⚠️' },
  { label: 'question', emoji: '❓' },
  { label: 'exclamation', emoji: '❗' },
  { label: 'smile cat', emoji: '😸' },
  { label: 'ghost', emoji: '👻' },
  { label: 'skull', emoji: '💀' },
  { label: 'alien', emoji: '👽' },
  { label: 'robot', emoji: '🤖' },
  { label: 'eyes', emoji: '👀' },
  { label: 'zzz', emoji: '💤' },
  { label: 'sunglasses', emoji: '😎' },
  { label: 'dancing', emoji: '💃' },
  { label: 'briefcase', emoji: '💼' },
  { label: 'computer', emoji: '💻' },
  { label: 'phone', emoji: '📱' },
  { label: 'camera', emoji: '📷' },
  { label: 'envelope', emoji: '✉️' },
  { label: 'bomb', emoji: '💣' },
]
